#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UVIE_RS_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== Building uvie-rs static library ==="
cd "$UVIE_RS_DIR"
cargo build --release

echo "=== Generating version info ==="
cd "$SCRIPT_DIR"
VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Info.plist)
COMMIT=$(cd "$UVIE_RS_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "unknown")
mkdir -p Sources/UVieKey/Generated
cat > Sources/UVieKey/Generated/Version.swift <<EOF
// Auto-generated by build.sh. Do not edit manually.
enum AppVersion {
    static let version = "$VERSION"
    static let commitHash = "$COMMIT"
    static let fullVersion = "v\(version)-\(commitHash)"
}
EOF

echo "=== Building UVieKey ==="

swift build \
    -Xswiftc -I"$UVIE_RS_DIR/include" \
    -Xswiftc -L"$UVIE_RS_DIR/target/release" \
    -Xlinker -luvie \
    "$@"

echo "Build complete! ($(date +%s) sec)"
echo "=== Build complete ==="
